# Generated by Django 4.0.4 on 2022-05-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id', models.IntegerField()),
                ('Date_added', models.DateField()),
                ('Is_listed', models.BooleanField()),
                ('Describe', models.TextField(max_length=1000)),
                ('Image', models.ImageField(upload_to='')),
                ('Price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Product_name', models.CharField(max_length=100)),
                ('Id_category', models.IntegerField()),
                ('Id_client', models.IntegerField()),
            ],
        ),
    ]
