# Generated by Django 4.0.4 on 2022-05-29 16:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Login', models.TextField(max_length=20)),
                ('Name', models.TextField(max_length=20)),
                ('Surname', models.TextField(max_length=20)),
                ('Adress', models.TextField(max_length=100)),
                ('Email', models.TextField(max_length=20)),
                ('Phone', models.TextField(max_length=20)),
                ('Birth_date', models.DateField()),
                ('City', models.TextField(max_length=20)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(max_length=1000)),
                ('Surname', models.TextField(max_length=1000)),
                ('Company_name', models.TextField(max_length=1000)),
                ('Phone', models.TextField(max_length=1000)),
                ('Email', models.TextField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Delivery',
                'verbose_name_plural': 'Deliveries',
            },
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Producer',
                'verbose_name_plural': 'Producers',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=100)),
                ('Price', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('Image', models.ImageField(blank=True, upload_to='')),
                ('Describe', models.TextField(max_length=500)),
                ('Date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('Is_listed', models.BooleanField()),
                ('Id_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.categories')),
                ('Id_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.client')),
                ('Producer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.producer')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='History_transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_of_buy', models.DateField()),
                ('Price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Status', models.CharField(max_length=100)),
                ('Excepted_day_of_delivery', models.DateField()),
                ('Id_client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.client')),
                ('Id_delivery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.delivery')),
            ],
            options={
                'verbose_name': 'History_transaction',
                'verbose_name_plural': 'History_transactions',
            },
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('Price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Id_client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.client')),
                ('Id_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.products')),
            ],
            options={
                'verbose_name': 'Basket',
                'verbose_name_plural': 'Baskets',
            },
        ),
    ]
