# Generated by Django 4.0.4 on 2022-05-22 19:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={'verbose_name': 'Basket', 'verbose_name_plural': 'Baskets'},
        ),
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='delivery',
            options={'verbose_name': 'Delivery', 'verbose_name_plural': 'Deliveries'},
        ),
        migrations.AlterModelOptions(
            name='history_transactions',
            options={'verbose_name': 'History_transaction', 'verbose_name_plural': 'History_transactions'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterField(
            model_name='basket',
            name='Id_client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.client'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='Id_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.products'),
        ),
        migrations.AlterField(
            model_name='client',
            name='Adress',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='City',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='Email',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='Login',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='Name',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='Phone',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='Surname',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='history_transactions',
            name='Id_client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='History_transaction_of_client', to='Products.client'),
        ),
        migrations.AlterField(
            model_name='history_transactions',
            name='Id_delivery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Courier', to='Products.client'),
        ),
        migrations.AlterField(
            model_name='products',
            name='Id_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.categories'),
        ),
        migrations.AlterField(
            model_name='products',
            name='Id_client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.client'),
        ),
        migrations.AlterField(
            model_name='products',
            name='Price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
