# Generated by Django 4.0.4 on 2022-05-22 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_alter_basket_options_alter_categories_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={},
        ),
        migrations.AlterModelOptions(
            name='delivery',
            options={},
        ),
        migrations.RemoveField(
            model_name='products',
            name='Id_client',
        ),
        migrations.AlterField(
            model_name='basket',
            name='Id_client',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='basket',
            name='Id_product',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='history_transactions',
            name='Id_client',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='history_transactions',
            name='Id_delivery',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='Id_category',
            field=models.IntegerField(null=True),
        ),
    ]
