# Generated by Django 4.0.4 on 2022-05-22 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_alter_products_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id', models.IntegerField()),
                ('Id_product', models.IntegerField()),
                ('Id_client', models.IntegerField()),
                ('Quantity', models.IntegerField()),
                ('Price', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id', models.IntegerField()),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id', models.IntegerField()),
                ('Login', models.TextField(max_length=1000)),
                ('Name', models.TextField(max_length=1000)),
                ('Surname', models.TextField(max_length=1000)),
                ('Adress', models.TextField(max_length=1000)),
                ('Email', models.TextField(max_length=1000)),
                ('Phone', models.TextField(max_length=1000)),
                ('Birth_date', models.DateField()),
                ('City', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id', models.IntegerField()),
                ('Name', models.TextField(max_length=1000)),
                ('Surname', models.TextField(max_length=1000)),
                ('Company_name', models.TextField(max_length=1000)),
                ('Phone', models.TextField(max_length=1000)),
                ('Email', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='History_transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id', models.IntegerField()),
                ('Id_client', models.IntegerField()),
                ('Date_of_buy', models.DateField()),
                ('Price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Status', models.CharField(max_length=100)),
                ('Excepted_day_of_delivery', models.DateField()),
                ('Id_delivery', models.IntegerField()),
            ],
        ),
    ]
