# Generated by Django 4.0.4 on 2022-05-22 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_alter_basket_options_alter_client_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Id_client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.client'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='Id_client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.client'),
        ),
        migrations.AlterField(
            model_name='products',
            name='Id_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.categories'),
        ),
    ]
