# Generated by Django 4.0.4 on 2022-05-28 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_products_producer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Producer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.producer'),
        ),
    ]
