# Generated by Django 4.0.4 on 2022-05-22 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_products_id_client_alter_basket_id_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='Id_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.products'),
        ),
        migrations.AlterField(
            model_name='history_transactions',
            name='Id_client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.client'),
        ),
    ]
