# Generated by Django 4.0.4 on 2022-05-22 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_basket_categories_client_delivery_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Basket',
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
        migrations.DeleteModel(
            name='History_transactions',
        ),
        migrations.AlterField(
            model_name='products',
            name='Describe',
            field=models.TextField(max_length=500),
        ),
    ]
