# Generated by Django 4.0.4 on 2022-05-22 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_alter_basket_id_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history_transactions',
            name='Id_delivery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.delivery'),
        ),
    ]
