# Generated by Django 4.0.4 on 2022-05-22 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_alter_history_transactions_id_delivery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={'verbose_name': 'Basket', 'verbose_name_plural': 'Baskets'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='delivery',
            options={'verbose_name': 'Delivery', 'verbose_name_plural': 'Deliveries'},
        ),
    ]
