# Generated by Django 4.0.4 on 2022-05-28 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0007_alter_basket_options_alter_client_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Date_added',
            field=models.DateField(blank=True),
        ),
    ]
