# Generated by Django 4.0.4 on 2022-05-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0008_alter_products_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Date_added',
            field=models.DateField(blank=True, null=True),
        ),
    ]
