# Generated by Django 4.0.4 on 2022-05-29 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0009_alter_products_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='Id_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.client'),
        ),
    ]
